"""initial sqlite schema

Revision ID: 770712788d4b
Revises: 
Create Date: 2026-08-30 22:41:44.230387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770712788d4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('state_json', sa.JSON(), nullable=True),
    sa.Column('question_json', sa.JSON(), nullable=True),
    sa.Column('answer_json', sa.JSON(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)

    op.create_table('primitive_requests',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('pseudocode', sa.Text(), nullable=True),
    sa.Column('sources_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('primitive_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_primitive_requests_status'), ['status'], unique=False)

    op.create_table('research_queue',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_queue_status'), ['status'], unique=False)

    op.create_table('research_sources',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('credibility', sa.Float(), nullable=True),
    sa.Column('scored_json', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('research_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_sources_domain'), ['domain'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('strategies',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('origin_type', sa.String(length=32), nullable=False),
    sa.Column('origin_id', sa.String(length=12), nullable=True),
    sa.Column('parent_id', sa.String(length=12), nullable=True),
    sa.Column('spec_json', sa.JSON(), nullable=False),
    sa.Column('risk_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategies_status'), ['status'], unique=False)

    op.create_table('backtests',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('strategy_id', sa.String(length=12), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('window_kind', sa.String(length=16), nullable=False),
    sa.Column('date_from', sa.String(length=10), nullable=True),
    sa.Column('date_to', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('trades_path', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('finished_at', sa.String(length=32), nullable=True),
    sa.Column('agent_run_id', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtests_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtests_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index('ix_backtests_strategy_window', ['strategy_id', 'window_kind'], unique=False)

    op.create_table('llm_usage',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('ts', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cache_read', sa.Integer(), nullable=False),
    sa.Column('cache_write', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('agent_run_id', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_ts'), ['ts'], unique=False)

    op.create_table('research_docs',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('source_id', sa.String(length=12), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('ingested_to_graph', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_docs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_docs_source_id'), ['source_id'], unique=False)

    op.create_table('teaching_sessions',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('root', sa.String(length=8), nullable=False),
    sa.Column('date_from', sa.String(length=32), nullable=True),
    sa.Column('date_to', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('compiled_strategy_id', sa.String(length=12), nullable=True),
    sa.Column('similarity_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['compiled_strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teaching_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_sessions_status'), ['status'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('backtest_id', sa.String(length=12), nullable=True),
    sa.Column('strategy_id', sa.String(length=12), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_backtest_id'), ['backtest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('teaching_events',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('session_id', sa.String(length=12), nullable=False),
    sa.Column('ts', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['teaching_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teaching_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_events_session_id'), ['session_id'], unique=False)

    op.create_table('teaching_trades',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('session_id', sa.String(length=12), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('entry_ts', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('exit_ts', sa.Integer(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('pnl_usd', sa.Float(), nullable=True),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('snapshot_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['teaching_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teaching_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_trades_session_id'), ['session_id'], unique=False)

    op.create_table('teaching_questions',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('session_id', sa.String(length=12), nullable=False),
    sa.Column('trade_id', sa.String(length=12), nullable=True),
    sa.Column('replay_ts', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('asked_at', sa.String(length=32), nullable=False),
    sa.Column('answered_at', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['teaching_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['teaching_trades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teaching_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_questions_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_questions_session_id'))

    op.drop_table('teaching_questions')
    with op.batch_alter_table('teaching_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_trades_session_id'))

    op.drop_table('teaching_trades')
    with op.batch_alter_table('teaching_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_events_session_id'))

    op.drop_table('teaching_events')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_findings_backtest_id'))

    op.drop_table('findings')
    with op.batch_alter_table('teaching_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_sessions_status'))

    op.drop_table('teaching_sessions')
    with op.batch_alter_table('research_docs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_docs_source_id'))

    op.drop_table('research_docs')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_ts'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_agent_run_id'))

    op.drop_table('llm_usage')
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.drop_index('ix_backtests_strategy_window')
        batch_op.drop_index(batch_op.f('ix_backtests_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_backtests_status'))
        batch_op.drop_index(batch_op.f('ix_backtests_agent_run_id'))

    op.drop_table('backtests')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_status'))
        batch_op.drop_index(batch_op.f('ix_strategies_parent_id'))

    op.drop_table('strategies')
    op.drop_table('settings')
    with op.batch_alter_table('research_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_sources_domain'))

    op.drop_table('research_sources')
    with op.batch_alter_table('research_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_queue_status'))

    op.drop_table('research_queue')
    with op.batch_alter_table('primitive_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_primitive_requests_status'))

    op.drop_table('primitive_requests')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))

    op.drop_table('agent_runs')
    # ### end Alembic commands ###
