"""knowledge facts

Revision ID: fd664d14dca5
Revises: 770712788d4b
Create Date: 2026-08-31 00:24:48.180962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd664d14dca5'
down_revision: Union[str, Sequence[str], None] = '770712788d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_facts',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('source_id', sa.String(length=12), nullable=True),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('credibility', sa.Float(), nullable=False),
    sa.Column('evidence_type', sa.String(length=24), nullable=True),
    sa.Column('embedding_json', sa.JSON(), nullable=True),
    sa.Column('ref_id', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('invalid_at', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_facts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_facts_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_facts_ref_id'), ['ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_facts_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_facts_source_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_facts_ref_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_facts_kind'))
        batch_op.drop_index(batch_op.f('ix_knowledge_facts_created_at'))

    op.drop_table('knowledge_facts')
    # ### end Alembic commands ###
